### ISSUE TITLE
Async uploading string to file on FTP

### ISSUE THREAD

**Issue by mr-bjerre** [aio-libs/aioftp#106]
Imagine I have a python application that produces some json output that I want to upload to a file on an FTP server.

How do I do that? Looking at [`upload`](https://github.com/aio-libs/aioftp/blob/master/aioftp/client.py#L912) I can only give a path to an existing file. How do you recommend to go ahead?

**Comment by pohmelie** [comment]
You should use [`upload_stream`](https://aioftp.readthedocs.io/client_api.html#aioftp.Client.upload_stream).

**Comment by mr-bjerre** [comment]
Oh somehow I missed the docs - thanks for what seems a great library.

I'm afraid my python skills is limited here though, do you mind adding a small snippet on how to?

```python
import asyncio
import aioftp
import io

async def upload_json(json, filename, host, port, login, password):
    async with aioftp.ClientSession(host, port, login, password) as client:
        client.upload_stream(filename, io.BytesIO(json.encode('utf8')))

print("Start upload")
upload_json('{"a": "test"}', "test.json", "server1.com", 21, "login", "password")
print("Continued without waiting for the upload to finish")
```

I was imagining something in the neighborhood of this but I'm sure it's not exactly right

**Comment by pohmelie** [comment]
Here is tutorial for `*_stream` family: https://aioftp.readthedocs.io/client_tutorial.html#advanced-download-and-upload-abort-restart
