### ISSUE TITLE
Leap year bug

### ISSUE THREAD

**Issue by decaz** [aio-libs/aioftp#109]
`LIST` doesn't return files of Feb 29.

The problem is here:
https://github.com/aio-libs/aioftp/blob/9fa19b106d6be2d38eeb885c5ad8f81338869da1/aioftp/client.py#L371

Reason: `Passing datetime.strptime('Feb 29', '%b %d') will fail since 1900 is not a leap year.` (https://docs.python.org/3/library/datetime.html#id8)

**Comment by pohmelie** [comment]
This already discussed in #107

**Comment by pohmelie** [comment]
Hm, did not close by `fixes`, strange.
