### ISSUE TITLE
data connection could not be established when using filezilla as ftp client

### ISSUE THREAD

**Issue by fpemud** [aio-libs/aioftp#120]
There's no firewall in my network.

The following is the content of filezilla message log window:
Command:	PORT 192,168,1,27,128,65
Response:	502 'port' not implemented
Command:	PASV
Response:	227-listen socket created
Response:	227 (0,0,0,0,135,179)
Command:	LIST
Error:	The data connection could not be established: ECONNREFUSED - Connection refused by server
Response:	150 list transfer started
Response:	425 Can't open data connection

The following is the aioftp log (in reverse order):
Jul 21 06:58:41 fpemud-workstation mirrors[8121]: closing connection from 192.168.1.27:48686
Jul 21 06:58:41 fpemud-workstation mirrors[8121]: ConnectionResetError
Jul 21 06:58:41 fpemud-workstation mirrors[8121]:     raise ConnectionResetError
Jul 21 06:58:41 fpemud-workstation mirrors[8121]:   File "/usr/lib64/python3.6/site-packages/aioftp/server.py", line 498, in parse_command
Jul 21 06:58:41 fpemud-workstation mirrors[8121]:     result = task.result()
Jul 21 06:58:41 fpemud-workstation mirrors[8121]:   File "/usr/lib64/python3.6/site-packages/aioftp/server.py", line 913, in dispatcher
Jul 21 06:58:41 fpemud-workstation mirrors[8121]: Traceback (most recent call last):
Jul 21 06:58:41 fpemud-workstation mirrors[8121]: dispatcher caught exception
Jul 21 06:58:33 fpemud-workstation mirrors[8121]: 502 'noop' not implemented
Jul 21 06:58:33 fpemud-workstation mirrors[8121]: NOOP
Jul 21 06:58:03 fpemud-workstation mirrors[8121]: 200
Jul 21 06:58:03 fpemud-workstation mirrors[8121]: TYPE I
Jul 21 06:57:33 fpemud-workstation mirrors[8121]: 200
Jul 21 06:57:33 fpemud-workstation mirrors[8121]: TYPE I
Jul 21 06:57:03 fpemud-workstation mirrors[8121]: 425 Can't open data connection
Jul 21 06:57:02 fpemud-workstation mirrors[8121]: 150 list transfer started
Jul 21 06:57:02 fpemud-workstation mirrors[8121]: LIST
Jul 21 06:57:02 fpemud-workstation mirrors[8121]: 227 (0,0,0,0,160,21)
Jul 21 06:57:02 fpemud-workstation mirrors[8121]: 227-listen socket created
Jul 21 06:57:02 fpemud-workstation mirrors[8121]: PASV
Jul 21 06:57:02 fpemud-workstation mirrors[8121]: 502 'port' not implemented
Jul 21 06:57:02 fpemud-workstation mirrors[8121]: PORT 192,168,1,27,167,83
Jul 21 06:57:02 fpemud-workstation mirrors[8121]: 200
Jul 21 06:57:02 fpemud-workstation mirrors[8121]: TYPE I
Jul 21 06:57:02 fpemud-workstation mirrors[8121]: 257 "/"
Jul 21 06:57:02 fpemud-workstation mirrors[8121]: PWD
Jul 21 06:57:02 fpemud-workstation mirrors[8121]: 502 'feat' not implemented
Jul 21 06:57:02 fpemud-workstation mirrors[8121]: FEAT
Jul 21 06:57:02 fpemud-workstation mirrors[8121]: 215 UNIX Type: L8
Jul 21 06:57:02 fpemud-workstation mirrors[8121]: SYST
Jul 21 06:57:02 fpemud-workstation mirrors[8121]: 230 anonymous login
Jul 21 06:57:02 fpemud-workstation mirrors[8121]: USER anonymous
Jul 21 06:57:02 fpemud-workstation mirrors[8121]: 502 'auth' not implemented
Jul 21 06:57:02 fpemud-workstation mirrors[8121]: AUTH SSL
Jul 21 06:57:02 fpemud-workstation mirrors[8121]: 502 'auth' not implemented
Jul 21 06:57:02 fpemud-workstation mirrors[8121]: AUTH TLS
Jul 21 06:57:01 fpemud-workstation mirrors[8121]: 220 welcome
Jul 21 06:57:01 fpemud-workstation mirrors[8121]: new connection from 192.168.1.27:48686

**Comment by fpemud** [comment]
This is the result when I use standard linux ftp client (it seems it is not usable because port command is not implemented):

fpemud@localhost ~ $ ftp fpemud-workstation.local
Connected to fpemud-workstation.local.
220 welcome
Name (fpemud-workstation.local:fpemud): 
502 'auth' not implemented
502 'auth' not implemented
SSL not available
230 anonymous login
Remote system type is UNIX.
Using binary mode to transfer files.
ftp> ls
502 'port' not implemented
ftp: bind: Address already in use
ftp> ls
502 'port' not implemented
ftp> bye
221 bye
fpemud@localhost ~ $

**Comment by pohmelie** [comment]
- Not sure what is wrong in this case, but `aioftp` waits between `Jul 21 06:57:02 fpemud-workstation mirrors[8121]: 150 list transfer started` and `Jul 21 06:57:03 fpemud-workstation mirrors[8121]: 425 Can't open data connection` for 1 second. This is default value to wait incomming data connection. After that, it timeouts, this is expected behavior.
- Yep, `PORT` is not implemented, because it forces the server to connect to client, but in real world this can't be achieved since NAT. And that is why this command is pretty useless. `ftp` have `-p` flag to use `PASV` instead of `PORT`, or you can use `pftp` command, where this flag is forced.

**Comment by fpemud** [comment]
This is the analyse result with "ftp -p". 192.168.1.27 is the host which is running aioftp server:

**ftp command interaction**
fpemud-workstation ~ # ftp -p 192.168.1.27 
Connected to 192.168.1.27.
220 welcome
Name (192.168.1.27:fpemud): 
502 'auth' not implemented
502 'auth' not implemented
SSL not available
230 anonymous login
Remote system type is UNIX.
Using binary mode to transfer files.
ftp> ls
227-listen socket created
227 (0,0,0,0,163,121)
ftp: connect: Connection refused
ftp>

**capture data connection packet on eth0, dstport is 163*256+121=41849, nothing captured**
fpemud-workstation ~ # tcpdump -i eth0 tcp port 41849
dropped privs to tcpdump
listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes

**capture data connection packet on loopback interface**
fpemud-workstation ~ # tcpdump -i lo tcp port 41849
dropped privs to tcpdump
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on lo, link-type EN10MB (Ethernet), capture size 262144 bytes
21:29:34.474287 IP 127.0.0.1.37692 > 127.0.0.1.41849: Flags [S], seq 3949466922, win 65495, options [mss 65495,sackOK,TS val 76306109 ecr 0,nop,wscale 7], length 0
21:29:34.474306 IP 127.0.0.1.41849 > 127.0.0.1.37692: Flags [R.], seq 0, ack 3949466923, win 0, length 0

So the reason is ftp client sends data connection packet to localhost, not the ftp server?!
I can't image such a bug exists in linux ftp command.
Please help analyze this.

**Comment by pohmelie** [comment]
How do you start aioftp server and what it logs?

**Comment by fpemud** [comment]
my aioftp server code is in _start() function in [this file](https://github.com/mirrorshq/mirrors/blob/master/lib/mc_server_ftp.py).

This is the ftp server log: (reverse order):
Jul 21 21:29:34 localhost mirrors[36215]: 227 (0,0,0,0,163,121)
Jul 21 21:29:34 localhost mirrors[36215]: 227-listen socket already exists
Jul 21 21:29:34 localhost mirrors[36215]: PASV
Jul 21 21:29:21 localhost mirrors[36215]: 227 (0,0,0,0,163,121)
Jul 21 21:29:21 localhost mirrors[36215]: 227-listen socket already exists
Jul 21 21:29:21 localhost mirrors[36215]: PASV
Jul 21 21:29:19 localhost mirrors[36215]: 227 (0,0,0,0,163,121)
Jul 21 21:29:19 localhost mirrors[36215]: 227-listen socket already exists
Jul 21 21:29:19 localhost mirrors[36215]: PASV
Jul 21 21:28:59 localhost mirrors[36215]: 227 (0,0,0,0,163,121)
Jul 21 21:28:59 localhost mirrors[36215]: 227-listen socket created
Jul 21 21:28:59 localhost mirrors[36215]: PASV
Jul 21 21:28:56 localhost mirrors[36215]: 215 UNIX Type: L8
Jul 21 21:28:56 localhost mirrors[36215]: SYST
Jul 21 21:28:56 localhost mirrors[36215]: 230 anonymous login
Jul 21 21:28:56 localhost mirrors[36215]: USER fpemud
Jul 21 21:28:56 localhost mirrors[36215]: 502 'auth' not implemented
Jul 21 21:28:56 localhost mirrors[36215]: AUTH TLS
Jul 21 21:28:56 localhost mirrors[36215]: 502 'auth' not implemented
Jul 21 21:28:56 localhost mirrors[36215]: AUTH SSL
Jul 21 21:28:55 localhost mirrors[36215]: 220 welcome
Jul 21 21:28:55 localhost mirrors[36215]: new connection from 192.168.1.42:47906

**Comment by pohmelie** [comment]
I don't know exactly what is your problem. I've just tested with `ftp` and `ls` works:
```
$ python -m aioftp 
aioftp v0.16.1
[02:28:46]: [aioftp.server] serving on 0.0.0.0:2121
[02:28:46]: [aioftp.server] serving on :::2121
[02:28:50]: [aioftp.server] new connection from 127.0.0.1:40630
[02:28:50]: [aioftp.server] 220 welcome
[02:28:51]: [aioftp.server] USER poh
[02:28:51]: [aioftp.server] 230 anonymous login
[02:28:51]: [aioftp.server] SYST 
[02:28:51]: [aioftp.server] 215 UNIX Type: L8
[02:28:55]: [aioftp.server] PASV 
[02:28:55]: [aioftp.server] 227-listen socket created
[02:28:55]: [aioftp.server] 227 (0,0,0,0,138,201)
[02:28:55]: [aioftp.server] LIST 
[02:28:55]: [aioftp.server] 150 list transfer started
[02:28:55]: [aioftp.server] 226 list transfer done
```
```
$ ftp -v -p 127.0.0.1 2121
Connected to 127.0.0.1.
220 welcome
Name (127.0.0.1:poh): 
230 anonymous login
Remote system type is UNIX.
Using binary mode to transfer files.
ftp> ls
227-listen socket created
227 (0,0,0,0,138,201)
150 list transfer started
-rw-rw-r-- 1 none none 11357 May 25  2018 license.txt
-rw-rw-r-- 1 none none 184429 Jan 10  2020 profile.log
-rw-rw-r-- 1 none none 18766 May 25  2018 ftpbench.py
-rw-rw-r-- 1 none none 76 Jul 24  2018 yoba.py
drwxrwxr-x 4 none none 4096 Mar  8  2019 .mypy_cache
-rw-rw-r-- 1 none none 400 Jun  7  2019 test-aiosocks.py
-rw-rw-r-- 1 none none 39 Mar 24  2019 setup.py
drwxrwxr-x 2 none none 4096 Mar 24  2019 dist
drwxrwxr-x 9 none none 4096 Jul 20 15:41 .git
-rw-rw-r-- 1 none none 1248 Jan  3  2018 main.py
-rw-rw-r-- 1 none none 1203 Dec  2  2015 tmp6.py
-rw-r--r-- 1 none none 53248 Jun 25 15:01 .coverage
drwxrwxr-x 3 none none 4096 Jul 21 05:56 .pytest_cache
-rw-rw-r-- 1 none none 675 Aug 10  2019 setup.cfg
-rw-rw-r-- 1 none none 599 Apr 14  2016 tmp21.py
-rw-rw-r-- 1 none none 769 Dec 30  2019 issue-104.py
-rw-rw-r-- 1 none none 1339 Jun  4  2016 with-uvloop.py
-rw-rw-r-- 1 none none 583 Dec  4  2019 issue-103.py
drwxrwxr-x 2 none none 4096 Apr 16  2017 .vscode
drwxrwxr-x 3 none none 4096 Jul 20 15:41 tests
-rw-rw-r-- 1 none none 3105 Dec 30  2019 .travis.yml
-rw-rw-r-- 1 none none 3439 Apr 15  2016 tmp-restore-upload-on-disconnect.py
-rw-rw-r-- 1 none none 7 Jun 17 20:36 .python-version
-rw-rw-r-- 1 none none 1443 Apr 22  2016 tmp-ftps.py
-rw-rw-r-- 1 none none 1028 Nov  5  2015 link-tmp.py
-rw-rw-r-- 1 none none 2231 Jan  3  2018 developer-tutorial.py
-rw-rw-r-- 1 none none 427 Nov 14  2015 tmp5.py
-rw-rw-r-- 1 none none 69017 Jun 25 15:01 coverage.xml
drwxrwxr-x 2 none none 4096 Nov  9  2017 __pycache__
-rw-rw-r-- 1 none none 612 Feb 19  2019 pull89-2.py
-rw-rw-r-- 1 none none 401 Dec 15  2015 tmp11.py
-rw-rw-r-- 1 none none 1028 Nov  5  2015 tmp.py
-rw-rw-r-- 1 none none 4434 Sep  8  2019 README.rst
-rw-rw-r-- 1 none none 1709 Dec 17  2015 tmp20.py
-rw-rw-r-- 1 none none 832 Dec  3  2015 tmp7.py
-rw-rw-r-- 1 none none 1397 May 24  2017 tmp-tls.py
-rw-rw-r-- 1 none none 451 Sep 27  2019 issue-100.py
drwxrwxr-x 4 none none 4096 Aug 30  2018 build
-rw-rw-r-- 1 none none 63 Nov  5  2015 tmp3.py
-rw-rw-r-- 1 none none 156 Mar 26  2019 .gitignore
-rw-rw-r-- 1 none none 317 Mar 26  2019 pytest.ini
drwxrwxr-x 21 none none 4096 Feb 24  2019 .eggs
-rw-rw-r-- 1 none none 131 Feb 23  2019 MANIFEST.in
-rw-rw-r-- 1 none none 14 Jan 12  2016 tmp12.py
-rw-rw-r-- 1 none none 10493899 Jan 10  2020 $testfile
-rw-rw-r-- 1 none none 7794 Jul 20 15:41 history.rst
-rw-rw-r-- 1 none none 55 Mar 24  2019 .coveragerc
-rw-rw-r-- 1 none none 17 Feb 28  2017 doc-requirements.txt
drwxrwxr-x 4 none none 4096 Aug 10  2019 docs
-rw-rw-r-- 1 none none 209 Nov 11  2015 tmp4.py
drwxrwxr-x 2 none none 4096 Jun 17 21:10 aioftp.egg-info
-rw-rw-r-- 1 none none 1502 Feb 20  2019 pull89.py
-rw-rw-r-- 1 none none 28 Jan 10  2020 server.py
-rw-rw-r-- 1 none none 995 Nov  2  2015 tmp2.py
drwxrwxr-x 3 none none 4096 Jul  9 16:07 aioftp
226 list transfer done
ftp> 
```

**Comment by fpemud** [comment]
In your test environment, the server and client are both running locally.
Put server and client on separate machines can produce my test result.

**Comment by fpemud** [comment]
**I installed lftp which is usable:**
fpemud@localhost ~/workspace $ lftp fpemud-workstation.local
lftp fpemud-workstation.local:~> ls                          
drwxr-xr-x 2 none none 4096 Jul 19 18:13 driveoff-drivepack
drwxr-xr-x 6 none none 4096 Mar 29  2011 gentoo
drwxr-xr-x 2 none none 4096 Jul 15 06:05 ppxclub-ftp-general
drwxr-xr-x 2 none none 4096 Jul 15 06:05 ppxclub-ftp-iso
drwxr-xr-x 3 none none 4096 Jul 20 19:03 ppxclub-ftp-rom
drwxr-xr-x 264 none none 24576 Jul 22 01:40 romsmania
lftp fpemud-workstation.local:/>

And I tested linux ftp client with a public ftp server:
fpemud@localhost ~/codes/netkit-ftp-0.17 $ ftp -p xxxxyyyy.com 555
Connected to xxxxyyyy.com.
220-Serv-U FTP Server v6.4 for WinSock ready...
220-============================
220 .....
220 ============================
Name (xxxxyyyy.com:fpemud): xxxxxxxxx
500 'AUTH': command not understood.
500 'AUTH': command not understood.
SSL not available
331 User name okay, need password.
Password:
230-ServUPlus 2.2 unregistered. 
230-[UL:0B][DL:907.4M][CT:1.11G][0/60 Sec Cache]
230 User logged in, proceed.
Remote system type is UNIX.
Using binary mode to transfer files.
ftp> ls
> 227 Entering Passive Mode (58,17,22,24,232,81)
150 Opening ASCII mode data connection for /bin/ls.
drw-rw-rw-   1 user     group           0 Mar 22 17:12 xxxxxx
drw-rw-rw-   1 user     group           0 Mar 23 20:34 xxxxxx
drw-rw-rw-   1 user     group           0 Nov  3  2019 .
drw-rw-rw-   1 user     group           0 Nov  3  2019 ..
226-Using UL/DL ratio 1/1, counting bytes over all sessions
    Current UL/DL ratio credit 1167975 kBytes
226 Transfer complete.
ftp> 

The reason is that linux ftp command uses the IP information contained in PASV response directly.
Should the server fill the real ip address in PASV response?
Perhaps it really is a linux ftp command bug since its version is only 0.17.

I guess it is the same reason why filezilla fails to connect aioftp server.

**Comment by pohmelie** [comment]
> Should the server fill the real ip address in PASV response?

What is «real ip address». Server have no way to now exact advertise address for client to connect to. Only client knows which ip address was used. There can be bunch of nodes between them.

> Should the client use the original server ip when the ip field in PASV response is "0,0,0,0"?

Yes. This is what most clients do. Anyway it is better for them to use EPSV
