### ISSUE TITLE
No release notes since 0.13

### ISSUE THREAD

**Issue by deansg** [aio-libs/aioftp#123]
This library has no release notes since version 0.13. This makes tracking the changes incredibly difficult, which can cause serious problems, especially since it seems like minor versions may include breaking changes (such as moving from 0.16.1 to 0.17).

**Comment by pohmelie** [comment]
All changes described in [history.rst](https://github.com/aio-libs/aioftp/blob/master/history.rst).

**Comment by deansg** [comment]
Maybe the old releases page should be deleted then? The duplication of a change log is confusing.

**Comment by pohmelie** [comment]
I'm not sure this is possible. See no option to disable https://github.com/aio-libs/aioftp/releases page.

**Comment by pohmelie** [comment]
Hm, I can delete it one by one, though.

**Comment by pohmelie** [comment]
Ok, I've removed all releases and remove `release` notes from main page.
