### ISSUE TITLE
`Socks redirect is not supported` error when using SOCKS5 proxy

### ISSUE THREAD

**Issue by alviezhang** [aio-libs/aioftp#124]
I tried following code to connect an implicit FTPS server via SOCKS5 proxy:

```python
import aioftp
client = aioftp.Client(socks_host='127.0.0.1', socks_port=7891, socks_version=5)
response = await client.connect('ftp.bjshomedelivery.com')
```

However, I got an error with message `Socks redirect is not supported`. It is a siosocks error
in `siosocks/protocol.py` file, if I removed the following line in above file, it works normally.
https://github.com/pohmelie/siosocks/blob/master/siosocks/protocol.py#L246
```python
if port != 0:
    raise ValueError("Socks redirect is not supported")
```

And I print the `port` variable to console, it was `7891` the SOCKS5 port I provided before.
So do anything wrong in my code? How do I suppose to fix this ?

**Comment by alviezhang** [comment]
I also filed a ticket to siosocks too.
https://github.com/pohmelie/siosocks/issues/3

**Comment by pohmelie** [comment]
Nice catch, will fix this in `siosocks` soon.
