### ISSUE TITLE
how to set net:connection-limit 2; ?

### ISSUE THREAD

**Issue by greut** [aio-libs/aioftp#128]
Hi, I'm looking for a way to limit the number of connections made by the aioftp client, any suggestions?

Thanks in advance.

**Comment by pohmelie** [comment]
There should be no more than two connections at any point on client side. Are you sure you have more? How to reproduce this situation?

**Comment by greut** [comment]
I do something along those lines, and it fails on `login`

```python
client = aioftp.Client()

await client.connect(host)
await client.login(login, password)

# aioftp.errors.StatusCodeError: Waiting for ('230', '33x') but got 421 [" I can't accept more than 2 connections as the same user"]
```

**Comment by greut** [comment]
same issue with `ftplib`, it's a deeper issue...

**Comment by pohmelie** [comment]
Maybe someone use same credentials for ftp server as it says «per user».
