### ISSUE TITLE
Update minimum python version in conda-forge recipe

### ISSUE THREAD

**Issue by dstansby** [aio-libs/aioftp#133]
This is a cross-post of https://github.com/conda-forge/aioftp-feedstock/issues/10, but I thought I would put it here in case it's more visible. The conda-forge recipe for aioftp 0.17 didn't have the minimum python version updated to 3.7, so it is installed for python 3.6. I'm not sure if there's an easy way to fix this, but we have encountered it downstream in sunpy (https://github.com/sunpy/sunpy/issues/4608).

**Comment by pohmelie** [comment]
> I'm not sure if there's an easy way to fix this

I'm not familiar with conda, but isn't it easy as change version in `meta.yaml`? https://github.com/conda-forge/aioftp-feedstock/blob/master/recipe/meta.yaml#L20

**Comment by nabobalis** [comment]
This will be fixed by https://github.com/conda-forge/aioftp-feedstock/pull/12
The existing anaconda packages have been patched to prevent installation on 3.6.
