### ISSUE TITLE
Blanket "except Exception" obfuscating server-specific parsing problems 

### ISSUE THREAD

**Issue by spolloni** [aio-libs/aioftp#144]
Hello and thanks for maintaining this useful package!

I am experiencing an issue very similar to [this one](https://github.com/aio-libs/aioftp/issues/104), where due to a server intricacy, `aioftp` is failing to list and parse the host's root directory.  

It took me a long while to figure this out, because the following line: 
https://github.com/aio-libs/aioftp/blob/2fe66a1cfa31ec9081f696f7cedc47182f8560b6/aioftp/client.py#L786

prevents the much more useful exception below from being raised:
https://github.com/aio-libs/aioftp/blob/2fe66a1cfa31ec9081f696f7cedc47182f8560b6/aioftp/client.py#L535

As an example, the following code:
```
import asyncio
import aioftp

async def main():
    async with aioftp.Client.context('ftp.kymartian.ky.gov') as client:
        print(await client.list())

asyncio.run(main())
```
 will NOT fail and simply print `[]`, which seems like an undesirable behavior. If the more informative ValueError exception was raised instead, it would have been much clearer that using the `parse_list_line_custom` argument was necessary.

Is there a specific reason for using very generic `try`/`except` here?

**Comment by pohmelie** [comment]
AFAIR, `try`/`except` was introduced for windows ftp servers support. Since they can return `dir` command output. What is your suggestion in this case?

**Comment by spolloni** [comment]
> Since they can return `dir` command output.

Sorry I don't follow. How would this be affected by removing the `try/except` ?

**Comment by pohmelie** [comment]
Sorry for a delay. I got your point and agreed, it's better not to shadow errors. Changed in https://github.com/aio-libs/aioftp/commit/2e0c31761094fb11628d96c9678c4faf44b569bc

Will release right after resolve one more issue.
