### ISSUE TITLE
Feature Request: ability to use `parse_list_line_custom` only as a fallback solution

### ISSUE THREAD

**Issue by spolloni** [aio-libs/aioftp#145]
somewhat related to issues [104](https://github.com/aio-libs/aioftp/issues/104)  and [144](https://github.com/aio-libs/aioftp/issues/144) 

I was wondering if there is any interest in implementing a "fallback" list line parser. 

Currently, any callable passed as `parse_list_line_custom` will take precedence over `parse_list_line_unix` and `parse_list_line_windows`. However, for client code dealing with the "occasional" odd server that requires a custom parser, I much rather define a "fallback" parser used in last resort than ALWAYS overriding the built in parsers.

[Here](https://github.com/palmetto/aioftp/commit/7a8dd6218ee1701e144948aab6ba69eef6f15e33) is an implementation of this, but alternatively maybe a `'last'/'first'` argument could be used to tell the `Client` in what order to use the custom parser.

**Comment by pohmelie** [comment]
I got your point, but is there something wrong with just raising a `ValueError` if your custom parser don't understand the line and want to try unix and windows parsers instead?

**Comment by spolloni** [comment]
the problem is that oftentimes the custom parser WILL understand the line, but I would prefer to use `self.parse_list_line_unix` or `self.parse_list_line_windows` when they work.

**Comment by pohmelie** [comment]
I add `parse_list_line_custom_first` argument, will release new version soon.

**Comment by spolloni** [comment]
thanks!
