### ISSUE TITLE
client.list(/dir/file) -> dir/file/file

### ISSUE THREAD

**Issue by kuk** [aio-libs/aioftp#146]
`client.list` works fine for path to directory

```
async create_client(...) as client:
    items = await client.list('/dir/')
    for item in items:
        print(item)

(PurePosixPath('/dir/2021-07-21.csv'), {'type': 'file', 'unix.mode': 420, 'unix.links': '1', 'unix.owner': '1071', 'unix.group': '1072', 'size': '26097629', 'modify': '20210722092300'})
(PurePosixPath('/dir/2021-08-01.csv'), {'type': 'file', 'unix.mode': 420, 'unix.links': '1', 'unix.owner': '1071', 'unix.group': '1072', 'size': '27152841', 'modify': '20210804061600'})
```

Docs say `client.list` also works for path for file https://aioftp.readthedocs.io/client_api.html#aioftp.Client.list

But if I pass path to file it duplicates filename

```
async create_client(...) as client:
    items = await client.list('/dir/2021-07-21.csv')
    for item in items:
        print(item)

(PurePosixPath('/dir/2021-07-21.csv/2021-07-21.csv'), {'type': 'file', 'unix.mode': 420, 'unix.links': '1', 'unix.owner': '1071', 'unix.group': '1072', 'size': '26097629', 'modify': '20210722092300'})
```

/dir/2021-07-21.csv -> /dir/2021-07-21.csv/2021-07-21.csv

**Comment by pohmelie** [comment]
It looks like a bug in `list` implementation. Will fix this.

**Comment by pohmelie** [comment]
Have no good idea how to resolve this. Since `LIST` there is not way to resolve is it `foo.txt/foo.txt` or just `foo.txt` path on client side. Maybe solution can be only for server side, but this wont affect existing ftp servers of course. Can you provide logs so I can understand is it a `LIST` or `MLSx` family request?

**Comment by pohmelie** [comment]
As [rfc959](https://datatracker.ietf.org/doc/html/rfc959) said:
```
If the pathname specifies a file then the server should send current information on the file
```
But there is no information about how to distinguish reports for `LIST foo.txt` if it is `foo.txt` or `foo.txt/foo.txt` file structure.

**Comment by pohmelie** [comment]
I add information to docs and some test checks in https://github.com/aio-libs/aioftp/commit/3b74b902d3dc9a4e8e18c8d218c910740c9a7471

**Comment by pohmelie** [comment]
I suggest you to check if original path is dir via `is_dir` call. `aioftp` can't call `is_dir` since this lead to recursion (`is_dir` use `stat`, which use `list`).

**Comment by kuk** [comment]
Thank you! Using is_dir now
