### ISSUE TITLE
Asynchronous permission check

### ISSUE THREAD

**Issue by amotzkau** [aio-libs/aioftp#154]
I'd like to create an FTP daemon that checks permissions by calling another service.

As far as I can see the corresponding hook would be the get_permissions function in the User class. But this is not a coroutine, so the check would block. Would it be possible to change that into an asynchronous function?

Or is there another way to achieve that with aioftp?

Thanks,
Alex

**Comment by pohmelie** [comment]
> Would it be possible to change that into an asynchronous function?

Yep, there is no problem to make this async. Released this in 0.21.3. You can check it out on pypi.

**Comment by amotzkau** [comment]
Oh, that was fast. Thank you very much.
