### ISSUE TITLE
Im not sure but downloads are bugging

### ISSUE THREAD

**Issue by Sly0511** [aio-libs/aioftp#158]
![image](https://user-images.githubusercontent.com/47339373/189274998-85007fa4-92d8-4309-a8b1-1ca65f4318ec.png)
![image](https://user-images.githubusercontent.com/47339373/189275021-812b8b52-e481-4b96-ad24-77ea4bd607d7.png)
![image](https://user-images.githubusercontent.com/47339373/189275069-13ff9e6a-a735-441b-ab05-062cd938c88f.png)
It's not working I can't understand why either

**Comment by pohmelie** [comment]
This situation described in docs:https://aioftp.readthedocs.io/client_tutorial.html#listing-paths

> In case of async for be careful, since asynchronous variation of list is lazy. It means that you can’t interact with server until you leave `async for` block. If you need list and interact with server you should use eager version of list

**Comment by Sly0511** [comment]
I see thank you very much, I see now my mistake, seems like I wasn't paying enough attention to the documentation, my apologies
Thank you once again and have a great day
