### ISSUE TITLE
Let's put `aioftp` under the `aio-libs` org on PyPI

### ISSUE THREAD

**Issue by webknjaz** [aio-libs/aioftp#171]
See the details @ https://github.com/orgs/aio-libs/discussions/26.

For this, we'll need somebody with Owner privileges to either give me access on PyPI (the username there is the same — webknjaz) or be invited to the org by me (for that I'd need the username of such an individual).

As a bonus, this will also allow us to set up secretless publishing from GHA to PyPI and get rid of the in-repo secrets.

cc @pohmelie

**Comment by pohmelie** [comment]
Sounds good to me. I add you as owner on pypi. Also, if it is relevant, than you can add me to aio-libs.

**Comment by webknjaz** [comment]
Alright, the project moved, and I adjusted the privileges for everybody to be more limiting. I also invited you to the org on PyPI.

I haven't removed the bot, because it requires setting up secretless publishing first. I'll circle back later.

**Comment by pohmelie** [comment]
Here is publishing error: https://github.com/aio-libs/aioftp/actions/runs/7352697402/job/20017783024

**Comment by webknjaz** [comment]
> ```console
> * `job_workflow_ref`: `aio-libs/aioftp/.github/workflows/ci-cd.yaml@refs/tags/0.22.0`
> ```

Rename `.yaml` to `.yml` and it'll work.

**Comment by webknjaz** [comment]
Also, remember to move building the artifacts into a job separate from uploading them. The build scripts shouldn't have access to the OIDC permission, because it opens up possibilities for the privilege escalation attacks through poisoning the build system.
