### ISSUE TITLE
Support python version older than 3.11

### ISSUE THREAD

**Issue by michael-septeo** [aio-libs/aioftp#172]
In 0.22 release, the minimal python version has been bumped to 3.11. It is a bit harsh for users, as this python version has only been out for a year or so, and 3.8 still has security support for months (see https://endoflife.date/python).

Many deployment platforms and linux distributions (in LTS versions) does not have python 3.11 bundled. Setting this requirement so high will limit the reach of this lib.

I'd suggest something more common, like 3.9, which still has 2 years to live.

**Comment by pohmelie** [comment]
Nice catch. Set to `>= 3.8` for `0.22.3`.
