### ISSUE TITLE
Point an aio-libs subdomain to RTD?

### ISSUE THREAD

**Issue by webknjaz** [aio-libs/aioftp#180]
http://aioftp.readthedocs.org in the repo links/meta/texts points to the outdated domain. RTD uses `.io` as a the canonical TLD nowadays. So that needs to be fixed. You can use https://aioftp.rtfd.io, for short.

Though, I wanted to suggest setting up a https://aioftp.aio-libs.org — I can put a CNAME into the DNS records but you'll still have to add the setting on RTD or give me access to do this myself.

**Comment by pohmelie** [comment]
I will investigate this later. Thank you for the information.

**Comment by pohmelie** [comment]
@webknjaz if you send me instruction I can do something, but I did not get why it will be better, than original domain. If I'm correctly understand mechanic, then if aio-libs.org will be down or something wrong with redirection, then nobody can reach documentation (until he will have original link to RTD).

**Comment by webknjaz** [comment]
Yeah, that's if someone messes up DNS or forgets to pay for the domain. We've moved a bunch of the projects to subdomains already. It's nice to have them bundled similarly.

Instructions: go to https://app.readthedocs.org/dashboard/aioftp/domains/create/, type in `aioftp.aio-libs.org`, make it canonical and save. That's it.

**Comment by webknjaz** [comment]
The RTD-provided link would still work, though. It should be possible to undo the canonical checkbox at any time.

**Comment by pohmelie** [comment]
@webknjaz done
