### ISSUE TITLE
info['modify'] year is always 1900

### ISSUE THREAD

**Issue by saulcruz** [aio-libs/aioftp#60]
Not sure if there is something wrong with the  self.parse_ls_date(s[:12]) in aioftp/client.py but when doing the following:

`
await client.list(dir_path)

`

All the years are  1900 for the **modify** attribute , when in Filezilla they're  shown as they should, I'm connecting to an anonymous ftp server. In fact I'm using an open data ftp server (ftp2.census.gov) if you'd like to try.

Is this something regarding the server, are we missing a new condition maybe during the parsing?

Thanks

**Comment by pohmelie** [comment]
Unfortunately I can't connect to this server. It looks down from here. Add logging at `DEBUG` level and rerun your test code. This will produce  server response so we can understand what is going on here.

**Comment by saulcruz** [comment]
thanks for your response, yeah it is unstable, however if you try it a couple times you will get in, (my workaround in the code to tackle this issue is to use tenacity and retry after a timeout)

You can try the following, if it doesn't connect kill it and try again
```
import tenacity
import asyncio
import aioftp
async def get_info(path, host='ftp2.census.gov', port=21, login='anonymous'):
    async with aioftp.ClientSession(host, port, login) as client:
        path_info = await client.list(path)
        print(path_info)

event_loop = asyncio.ProactorEventLoop()
asyncio.set_event_loop(event_loop)
event_loop.run_until_complete(get_info(path="/geo/tiger/TIGER2017/ZCTA5"))
event_loop.close()
```

or using tenacity

```
import asyncio
import aioftp
import logging
from tenacity import retry, stop_after_attempt, wait_fixed

logging.basicConfig(level=logging.DEBUG)

@retry(stop=stop_after_attempt(10), wait=wait_fixed(1))
async def get_info(path, host='ftp2.census.gov', port=21, login='anonymous'):
    async with aioftp.ClientSession(host, port, login, socket_timeout=2) as client:
        path_info = await client.list(path)
        print(path_info)


# Test async execution
event_loop = asyncio.ProactorEventLoop()
asyncio.set_event_loop(event_loop)
event_loop.run_until_complete(get_info(path="/geo/tiger/TIGER2017/ZCTA5"))
event_loop.close()
```



When it works I get the following:

[(PurePosixPath('/geo/tiger/TIGER2017/ZCTA5/tl_2017_us_zcta510.zip'), {'type': 'file', 'unix.mode': 436, 'unix.links': '1', 'unix.owner': '889', 'unix.group': 'i-geo', 'size': '532724352', 'modify': '19000927232500'})]

and the logging info:

```
DEBUG:asyncio:Using proactor: IocpProactor
INFO:aioftp.client:220-    **WARNING**WARNING**WARNING**WARNING**WARNING****WARNING**WARNING**
INFO:aioftp.client:220-
INFO:aioftp.client:220-    This is a Census Bureau computer system. Census Bureau computer
INFO:aioftp.client:220-    systems are provided for the processing of official U.S. Government
INFO:aioftp.client:220-    information only. All data contained within Census Bureau computer
INFO:aioftp.client:220-    systems is owned by the Census Bureau, and may be monitored,intercepted, recorded, read,
INFO:aioftp.client:220-    copied, or captured in any manner and disclosed in any manner, by
INFO:aioftp.client:220-    authorized personnel. THERE IS NO RIGHT OF PRIVACY IN THIS SYSTEM.
INFO:aioftp.client:220-    System personnel may disclose any potential evidence of crime found
INFO:aioftp.client:220-    on Census Bureau computer systems to appropriate authorities. USE OF
INFO:aioftp.client:220-    THIS SYSTEM BY ANY USER, AUTHORIZED OR UNAUTHORIZED, CONSTITUTES
INFO:aioftp.client:220-    CONSENT TO THIS MONITORING, INTERCEPTION RECORDING, READING, COPYING,
INFO:aioftp.client:220-    CAPTURING, and DISCLOSURE OF COMPUTER ACTIVITY. Use of this computer
INFO:aioftp.client:220-    without authorization or for unauthorized purposes is a violation of
INFO:aioftp.client:220-    federal law and punishable by fines or imprisonment (Public Law 99-474).
INFO:aioftp.client:220-
INFO:aioftp.client:220-    **WARNING**WARNING**WARNING**WARNING**WARNING****WARNING**WARNING**
INFO:aioftp.client:220
INFO:aioftp.client:USER anonymous
INFO:aioftp.client:331 Please specify the password.
INFO:aioftp.client:PASS anon@
INFO:aioftp.client:230-Server: ftp2.census.gov
INFO:aioftp.client:230-
INFO:aioftp.client:230-Personal Identifiable Information (PII) shall not be placed on the FTP
INFO:aioftp.client:230-server without prior special arrangement and in conjunction with ITSO.
INFO:aioftp.client:230-
INFO:aioftp.client:230-NOTE: The data available for anonymous FTP download on this FTP server are
INFO:aioftp.client:230-also available over the Web:
INFO:aioftp.client:230-http://www2.census.gov
INFO:aioftp.client:230 Login successful.
INFO:aioftp.client:TYPE I
INFO:aioftp.client:200 Switching to Binary mode.
INFO:aioftp.client:PASV
INFO:aioftp.client:227 Entering Passive Mode (148,129,75,35,19,150)
INFO:aioftp.client:MLSD /geo/tiger/TIGER2017/ZCTA5
INFO:aioftp.client:500 Unknown command.
INFO:aioftp.client:TYPE I
INFO:aioftp.client:200 Switching to Binary mode.
INFO:aioftp.client:PASV
INFO:aioftp.client:227 Entering Passive Mode (148,129,75,35,23,151)
INFO:aioftp.client:LIST /geo/tiger/TIGER2017/ZCTA5
INFO:aioftp.client:150 Here comes the directory listing.
INFO:aioftp.client:226 Directory send OK.
INFO:aioftp.client:QUIT
[(PurePosixPath('/geo/tiger/TIGER2017/ZCTA5/tl_2017_us_zcta510.zip'), {'type': 'file', 'unix.mode': 436, 'unix.links': '1', 'unix.owner': '889', 'unix.group': 'i-geo', 'size': '532724352', 'modify': '19000927232500'})]
INFO:aioftp.client:221 Goodbye.
DEBUG:asyncio:taking long time to close proactor
```

**Comment by pohmelie** [comment]
Hm… unfortunately client does not log extra connection raw lines from server at this moment. Add extra log/print statement right after `readline` at [client.py#624](https://github.com/pohmelie/aioftp/blob/master/aioftp/client.py#L624) and rerun test code, since I have no success with connection to server at all.

**Comment by NickG123** [comment]
Hey @pohmelie, if it helps, I am able to connect to this server,  The raw data received back from the above script looks like the following:

```
b'-rw-rw-r--    1 889      i-geo    532724352 Sep 27 23:25 tl_2017_us_zcta510.zip\r\n'
```

**Comment by pohmelie** [comment]
@NickG123 
Thank you for help. Now we can understand reason of 1900 year.
`parse_ls_date` receive string `Sep 27 23:25`, it is parsed with `time.strptime(s, "%b %d %H:%M")`, which result to `1900` year.
AFAIK such modify string allowed if file is not older than year(?) since now, so it looks like a bug.
@jw4js 
what do you think?

**Comment by rsichny** [comment]
>AFAIK such modify string allowed if file is not older than year(?)

commonly used for files that are not older than half a year (in most implementations 15778476 seconds)

>The <date and time> field shall contain the appropriate date and timestamp of when the file was last modified. In the POSIX locale, the field shall be the equivalent of the output of the following date command:
>
>date "+%b %e %H:%M"
>
>if the file has been modified in the last six months, or:
>
>date "+%b %e %Y"
>
>(where two <space>s are used between %e and %Y ) if the file has not been modified in the last six months or if the modification date is in the future

(c) `man ls`

**Comment by pohmelie** [comment]
@rsichny 
Ah, right you are! Thanks!
