### ISSUE TITLE
Access user object from AbstractPathIO

### ISSUE THREAD

**Issue by jacobtomlinson** [aio-libs/aioftp#66]
I'm trying to implement my own specialised FTP server by extending the `AbstractUserManager` and `AbstractPathIO`. However I have a requirement for the `AbstractPathIO` based class to know which user is accessing it. 

I'm basically passing the provided username and password onto a third-party service and need to be able to access them within every `AbstractPathIO` operation.

I would be tempted to make the `connection` object an arg on every `AbstractPathIO` method and pass it through on every call. However this is a large API change, and perhaps someone can think of a better way.

**Comment by pohmelie** [comment]
It looks like you can write your own `UserManager` and `User`. `User.get_permission` is what you looking for. Though it is not async yet, but I see no reasons for this not to be async.

**Comment by jacobtomlinson** [comment]
I've written a `UserManager` and I guess I could write a `User`. But how would you recommend accessing the user from within a `PathIO` method as it doesn't have access to the connection object?

**Comment by pohmelie** [comment]
You don't need to access user from `PathIO`, since you can check permissions in `User.get_permission` and forbid or allow futher interaction with `PathIO`.

**Comment by jacobtomlinson** [comment]
I do need access. Within the `PathIO` method I need to make a call to a third-party API to do the actual file operations. To make the call I need the username and password from the `User` object.

**Comment by pohmelie** [comment]
Oh, I see… In this case there is two options:
* pass `connection` to all `PathIO` methods
* create `PathIO` on incoming connection in `dispatcher` and pass `connection` to `__init__` method, so it will be accessible from any `PathIO` method.

**Comment by pohmelie** [comment]
More to say, I see no reasons for second one not to be in upstream, so your pull is welcome. :wink:

**Comment by pohmelie** [comment]
Yes, that looks cleaner for me.

**Comment by pohmelie** [comment]
I refactor some your code. It looks like now it should works as you expect.

**Comment by jacobtomlinson** [comment]
Thanks!
