### ISSUE TITLE
Inconsistent EPSV return message format.

### ISSUE THREAD

**Issue by p4l1ly** [aio-libs/aioftp#69]
Hi, you cannot rely on this format https://github.com/aio-libs/aioftp/blob/master/aioftp/client.py#L942

In my case I've got `' Entering Extended Passive Mode (|||50006|).'` and the period causes ValueError.

**Comment by pohmelie** [comment]
As [RFC2428](https://tools.ietf.org/html/rfc2428) said:
```
The text returned in response to the EPSV command MUST be:
<text indicating server is entering extended passive mode> (<d><d><d><tcp-port><d>)
```
So, the format is strict and this server do not respect it. I don't know good enough solution for this right now. Do you have any ideas?

**Comment by rsichny** [comment]
@pohmelie the message should be `Entering Extended Passive Mode (|||50006|)` (no `.` in the end)

**Comment by pohmelie** [comment]
@rsichny I know. AFAIR the problem is not with `aioftp` server, but with some third server. Since, `aioftp` do not add dot at the end of message. https://github.com/aio-libs/aioftp/blob/master/aioftp/server.py#L474-L486

**Comment by pohmelie** [comment]
@p4l1ly 
What server do you use?

**Comment by p4l1ly** [comment]
It says it is Serv-U 15.1.3.3

**Comment by p4l1ly** [comment]
Yeah, it definitely looks like the server does not respect the standard. However, you might want to consider parsing the messages [the same way](https://github.com/python/cpython/blob/3.6/Lib/ftplib.py#L859) as `ftplib` to support more servers.

**Comment by pohmelie** [comment]
@p4l1ly 
Actually, cpython `ftplib` parsing code is not accurate:
``` python
bpython version 0.16 on top of Python 3.6.2 /home/broomrider/.pyenv/versions/3.6.2-kron/envs/packaging/bin/python
>>> import ftplib
>>> ftplib.parse229("229 foo bar ha-ha (|||666|)", ["localhost"])
('localhost', 666)
>>> ftplib.parse229("229 foo bar (ha-ha) (|||666|)", ["localhost"])
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    ftplib.parse229("229 foo bar (ha-ha) (|||666|)", ["localhost"])
  File "/home/broomrider/.pyenv/versions/3.6.2-kron/lib/python3.6/ftplib.py", line 870, in parse229
    raise error_proto(resp)
ftplib.error_proto: 229 foo bar (ha-ha) (|||666|)
>>>
```
More to say, as RFC said:
```
The delimiter character MUST be one of the ASCII
   characters in range 33-126 inclusive.
```
So, the `(` or `)` can be used. But yes, I got your idea of more flexible parsing. Need some time to think about.

**Comment by NickG123** [comment]
I have run into the same issue with vsFTPd 2.2.2.  Are there any plans to add leniency here?

Thanks,
Nick

**Comment by pohmelie** [comment]
@NickG123 
This is fixed already, but not released on pypi. You can use upstream version from github, or wait for couple of weeks, when I will resolve other issues and make new release.

**Comment by NickG123** [comment]
Hi @pohmelie,
I missed that commit, apologies.
However, I guess I am running into a very similar, but not exactly the same error.
The place I am running into a problem is on [this line](https://github.com/aio-libs/aioftp/blob/bac9072e0b447237e7e13e0341e90b84f7dbedfe/aioftp/client.py#L962)
If you want me to open a separate issue, let me know.

**Comment by pohmelie** [comment]
@NickG123 
Try upstream version at first. If error is present, than create new issue.
