### ISSUE TITLE
How to set passive mode PASV ?

### ISSUE THREAD

**Issue by ramstein74** [aio-libs/aioftp#70]
Hello ,
How to set passive mode PASV ?

**Comment by pohmelie** [comment]
`PASV` will be tried after `EPSV` not implemented return code (502)

**Comment by ramstein74** [comment]
i used the traditional ftplib like this

import ftplib
ftp1 = ftplib.FTP(FtpServer,'cires','cires')
ftp1.set_pasv(False)

how do i used your aioftp to do the same set_pasv(False)? ??

regards

2018-02-06 16:54 GMT+00:00 Nikita Melentev <notifications@github.com>:

**Comment by pohmelie** [comment]
`set_pasv(False)` mean use «active» mode and `PORT` command. `aioftp` do not support `PORT` until someone will implement this. #16

**Comment by pohmelie** [comment]
Further discussion in #16
