### ISSUE TITLE
help

### ISSUE THREAD

**Issue by emans841** [aio-libs/aioftp#74]
p install aioftp
Collecting aioftp
  Using cached https://files.pythonhosted.org/packages/da/1e/34eff8522111f4a33f6c5af79bc211009beca5ddc2ede1e44c9b801f8d5e/aioftp-0.10.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-wRCvSQ/aioftp/setup.py", line 10, in <module>
        (BASE_PATH / "aioftp" / "__init__.py").read_text(),
    AttributeError: 'PosixPath' object has no attribute 'read_text'

**Comment by pohmelie** [comment]
[`read_text`](https://docs.python.org/3/library/pathlib.html?highlight=read_text#pathlib.Path.read_text) requires python 3.5+ (so `aioftp` do). What version of python do you use?

**Comment by asvetlov** [comment]
@pohmelie I think adding `python_requires` to `setup.py` like [here](https://github.com/aio-libs/aiohttp/blob/master/setup.py#L128) makes sense

**Comment by pohmelie** [comment]
@asvetlov sure, thanks!
