### ISSUE TITLE
SSL Memory Leak, a lot of CLOSE_WAIT state in netstat

### ISSUE THREAD

**Issue by PonyPC** [aio-libs/aioftp#88]
aioftp server with ssl

some connection cancel before ssl handshake finishing.

the aiohttp has this problem too, maybe python low-level memory leak?

**Comment by pohmelie** [comment]
Can you add some minimal example to reproduce?

**Comment by PonyPC** [comment]
Confirmed: python sslproto module low level leak
Emm...after deep searching, I found a ugly way to resolve this problem.
Using uvloop.

Just replace your asyncio.new_event_loop() to uvloop.new_event_loop()
then asyncio.set_event_loop(loop)
everything will be ok. The uvloop has patched asyncio and sslproto module, ssl socket is no more leaked!

According to python contributor, they said they would rewrite the whole ssl module in python 3.8 ( maybe)  due to design problem of ssl socket. So before releasing python 3.8, you can just using uvloop.

**Comment by pohmelie** [comment]
Is threre any relevant issue on python bug tracker?

**Comment by PonyPC** [comment]
Sure.
https://bugs.python.org/issue29406
https://bugs.python.org/issue30698

**Comment by pohmelie** [comment]
Alright, I think this can be closed, since this is python issue. @PonyPC, feel free to suggest reopen if need.
