### ISSUE TITLE
Download file without checking if it exists

### ISSUE THREAD

**Issue by para-dise** [aio-libs/aioftp#90]
Is this possible?
I connect to an FTP server that seems to time out when listing files. Uploading and almost everything else works fine.
However, I get
aioftp.errors.StatusCodeError: Waiting for ('2xx',) but got 550 [" Can't check for file existence"]
whenever I try to download a file, this may be related to not being able to use files.
The code I'm currently using is
`await ftpclient.download("file.txt", "tmp/file.txt", write_into=False)`
I can't seem to find a way for aioftp to skip the file existence check.

OS: Ubuntu 16.04
aioftp ver: 0.10.1 (Using it because of py 3.5.2 support)

**Comment by pohmelie** [comment]
Are you sure server can't list files? Is this server public so I can try it out?

Anyway, there are couple solutions:
* Use `download_stream` directly (this mentioned in documentation)
* Override `is_file` to return `True` always.
    ``` python
    class MyClient(Client):
        async def is_file(self, path):
            return True
    ```

**Comment by para-dise** [comment]
> Are you sure server can't list files? Is this server public so I can try it out?
> 
> Anyway, there are couple solutions:
> 
> * Use `download_stream` directly (this mentioned in documentation)
> * Override `is_file` to return `True` always.
>   ```python
>   class MyClient(Client):
>       async def is_file(self, path):
>           return True
>   ```

I tried connecting via FTP and doing `ls` and the server seems to time out.
The FTP server is offered by gtrhost (client.gtrhost.com), if you register you can create an FTP account.
Also, thank you, I'll give your solution a try

**Comment by pohmelie** [comment]
> client.gtrhost.com

Have no success with this service, looks like it is down or phishing site.

**Comment by para-dise** [comment]
If you want I can make you an FTP account on it to test

**Comment by pohmelie** [comment]
This will be great!

**Comment by para-dise** [comment]
> This will be great!

Sorry, the host is having uh some issues, they aren't the best 😂 I'll try some other day.
![screenshot from 2019-02-21 14-46-45](https://user-images.githubusercontent.com/20133381/53177321-b7dde180-35e7-11e9-9126-c16b871a6ff9.png)
![screenshot from 2019-02-21 14-43-55](https://user-images.githubusercontent.com/20133381/53177323-b8767800-35e7-11e9-8f80-7f7c9f75c709.png)
Meanwhile, thanks a lot for your help.
