### ISSUE TITLE
Does aioftp support FTPES  (FTP server over explicit TLS/SSL)

### ISSUE THREAD

**Issue by saulcruz** [aio-libs/aioftp#93]
`from ftplib import FTP_TLS`

Using ftplib I was able to connect to my FTP server over explicit TLS/SSL in Python, I have not found a way to asynchronously download files using the aioftp library and FTPS. Does it only support plain FTP?  If it supports FTPES would you please provide an example? 

**Update**
I noticed that this feature was added https://github.com/aio-libs/aioftp/pull/81 

Does the same example in the README work? or are there any additional steps to connect to the FTP over explicit TLS/SSL ? 

I'm getting the following error:
`line 689, in do_handshake`
`ssl.SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:847)`

```python
import asyncio
import aioftp


async def get_mp3(host, port, login, password):
    async with aioftp.ClientSession(host, port, login, password, ssl=True) as client:
        for path, info in (await client.list(recursive=True)):
            if info["type"] == "file" and path.suffix == ".mp3":
                await client.download(path)


loop = asyncio.get_event_loop()
tasks = (
    get_mp3("server1.com", 21, "login", "password")),
    get_mp3("server2.com", 21, "login", "password")),
    get_mp3("server3.com", 21, "login", "password")),
)
loop.run_until_complete(asyncio.wait(tasks))
loop.close()
```

Thanks for this library :)

**Comment by pohmelie** [comment]
@saulcruz 
> Does the same example in the README work?

`ssl=True` just passed to [`open_connection`](https://docs.python.org/3/library/asyncio-eventloop.html?highlight=create_connection#asyncio.loop.create_connection). No magic (even no code at all :smile: ) here from aioftp library with ssl. So, yes, it works.

**Comment by saulcruz** [comment]
Interesting, not working for me :( not sure what is wrong or different in my server. It works when using fptlib and the FTP_TLS

>>> from ftplib import FTP_TLS
>>> ftps = FTP_TLS('ftp.python.org')
>>> ftps.login()           # login anonymously before securing control channel
>>> ftps.prot_p()          # switch to secure
>>> ftps.retrlines('LIST')

**Comment by rsichny** [comment]
explicit mode is not implemented at this point, see #37

**Comment by pohmelie** [comment]
Oh, my bad. I misread "explicit". Only implicit mode supported right now. @rsichny, thanks!

**Comment by saulcruz** [comment]
Thanks @pohmelie  and @rsichny  will find a workaround then

**Comment by pohmelie** [comment]
Further discussion in #37
