### ISSUE TITLE
Remove dependency of twunnel3

### ISSUE THREAD

**Issue by purpleskyfall** [aio-libs/aioftp#94]
The package [twunnel3](https://github.com/jvansteirteghem/twunnel3) hasn't update more than 3 years, now it's incompatible with Python 3.5 or later.

Should aioftp drop the dependency of twunnel3 or maintain a fork by aio-libs?

**Comment by pohmelie** [comment]
`aioftp` have no `twunnel3` dependency. You mean remove `twunnel3` from readme and documentation?

**Comment by purpleskyfall** [comment]
`aioftp` using `twunnel3` for proxied FTP server connection. @pohmelie

**Comment by pohmelie** [comment]
@purpleskyfall 
It does not use it directly. There is no `twunnel3`-aware code in `aioftp`.

**Comment by purpleskyfall** [comment]
I have a question: how can I using `aioftp` for a proxied FTP server without `twunnel3`? @pohmelie

**Comment by pohmelie** [comment]
It looks like it is possible with [aiosocks](https://pypi.org/project/aiosocks)

**Comment by purpleskyfall** [comment]
But `aiosocks` don't support the http proxy server. Anyway, the documents of `aioftp` should remove `twunnel3`, I think.

**Comment by pohmelie** [comment]
How do you expect `FTP` to work over `HTTP`? :rofl:  
Yes, `twunnel3` will be removed right after I will find proper soution to use `SOCKS` proxy in aioftp.

**Comment by pohmelie** [comment]
`twunnel3` replaced with `siosocks` in more native manner. Thank you for report!
