### ISSUE TITLE
Client.list() should return info['modify'] as datetime

### ISSUE THREAD

**Issue by decaz** [aio-libs/aioftp#99]
I think `Client.format_date_time` is redundant and it's more convenient to get `datetime.datetime` object instead of formatted string.

**Comment by pohmelie** [comment]
Yes, sounds right. But we have `MLSx` parser, which do not post process path facts and all datetimes are strings as they comes from server. So, in case of `LIST` parser will return `datetime` object global facade `list` will return different types for different servers. This sounds bad.  
On the other hand is parsing both, but "time" is very difficult to do right, there are lots of libs trying to solve it smoothly and trying to implement part of them or trying to use them internaly smells. Let user decide what to do with time strings. Feel free to make more strong point on why this needs to be done.

**Comment by decaz** [comment]
I understand. But according to the `MLSx` [syntax of a time value](https://tools.ietf.org/html/rfc3659#section-2.3) couldn't `BaseClient.parse_mlsx_line` parse "Modify" string and convert it to the `datetime.datetime` object?

**Comment by pohmelie** [comment]
If we take conversion to datetime objects on our shoulders, then we must be consistent and parse all of possible facts. I'm not sure not big it is, but maybe there can be creation time. Also, if we implement parser on our side we should provide a method to override it.

**Comment by pohmelie** [comment]
Also, right now we provide as much `MLSx` info as we can, since we don't do conversions and not trying to guess type, but right after we start convertions there will a reasonable quetsion. Why we convert modification time string to datetime object, but do not convert file size, for example?

**Comment by decaz** [comment]
OK, I guess it can be closed for now.
